apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: creepy-flamingo-go
  janus-idp.io/tekton: creepy-flamingo-go
  backstage.io/kubernetes-id: creepy-flamingo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: creepy-flamingo-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
